const initialState = {
    patients:[{
        id: 1,
        name: "John Doe",
        dateOfBirth: "13-03-1992",
        age: 14,
        gender: "Male",
        address: "Parsnip St. East Legon",
        phoneNumber: "0203049937",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
    
      {
        id: 2,
        name: "Sandra Mensah",
        dateOfBirth: "20-03-1997",
        age: 23,
        gender: "Female",
        address: "Klagon, Accra",
        phoneNumber: "0579853237",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 3,
        name: "Lois Lartey",
        dateOfBirth: "13-08-1972",
        age: 39,
        gender: "Female",
        address: "Mango St. East Legon",
        phoneNumber: "0243049937",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 4,
        name: "Kelvin Sarsu",
        dateOfBirth: "15-03-1985",
        age: 13,
        gender: "Male",
        address: "Orange St. East Legon",
        phoneNumber: "0243869937",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 5,
        name: "Katelyn Boakye",
        dateOfBirth: "31-05-2011",
        age: 18,
        gender: "Female",
        address: "Korlegonnor, Accra",
        phoneNumber: "0266849937",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 6,
        name: "Samuel Nartey",
        dateOfBirth: "03-11-1972",
        age: 34,
        gender: "Male",
        address: "Kwame Nkrumah Circle, Accra",
        phoneNumber: "0203946287",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 7,
        name: "Cynthia Bills",
        dateOfBirth: "23-09-1962",
        age: 54,
        gender: "Female",
        address: "Nima, Accra",
        phoneNumber: "054479347",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 8,
        name: "Jack Harris",
        dateOfBirth: "13-03-1995",
        age: 25,
        gender: "Male",
        address: "Sowutuom, Accra",
        phoneNumber: "0244549937",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 9,
        name: "Mary Jane",
        dateOfBirth: "13-03-1992",
        age: 23,
        gender: "Female",
        address: "Parsnip St. East Legon",
        phoneNumber: "0203049937",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 10,
        name: "Abena Korkor",
        dateOfBirth: "13-03-1992",
        age: 39,
        gender: "Female",
        address: "Parsnip St. East Legon",
        phoneNumber: "0203049937",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 11,
        name: "Akwasi Bini",
        dateOfBirth: "13-03-2009",
        age: 13,
        gender: "Male",
        address: "Algon St. Tema",
        phoneNumber: "0238563945",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 12,
        name: "Esther Owusua",
        dateOfBirth: "20-07-2002",
        age: 19,
        gender: "Female",
        address: "Latebiokorshie, Accra",
        phoneNumber: "0544829306",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 13,
        name: "Jacob Sower",
        dateOfBirth: "13-12-1982",
        age: 34,
        gender: "Male",
        address: "Lapaz, Accra",
        phoneNumber: "0507291726",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 14,
        name: "Cassandra Smalls",
        dateOfBirth: "10-06-1959",
        age: 54,
        gender: "Female",
        address: "Lagoon St Dansoman",
        phoneNumber: "0578192712",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 15,
        name: "Lewis Brown",
        dateOfBirth: "13-03-1992",
        age: 67,
        gender: "Male",
        address: "Awoshie, Accra",
        phoneNumber: "0524808128",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 16,
        name: "Simon Adams",
        dateOfBirth: "13-03-1992",
        age: 54,
        gender: "Male",
        address: "Labone, Accra",
        phoneNumber: "0203049937",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 17,
        name: "Henry Delali",
        dateOfBirth: "13-03-1989",
        age: 29,
        gender: "Male",
        address: "James Town, Accra",
        phoneNumber: "0503647834",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
    ],
    patientsTally:[{
        id: 1,
        name: "John Doe",
        dateOfBirth: "13-03-1992",
        age: 14,
        gender: "Male",
        address: "Parsnip St. East Legon",
        phoneNumber: "0203049937",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
    
      {
        id: 2,
        name: "Sandra Mensah",
        dateOfBirth: "20-03-1997",
        age: 23,
        gender: "Female",
        address: "Klagon, Accra",
        phoneNumber: "0579853237",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 3,
        name: "Lois Lartey",
        dateOfBirth: "13-08-1972",
        age: 39,
        gender: "Female",
        address: "Mango St. East Legon",
        phoneNumber: "0243049937",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 4,
        name: "Kelvin Sarsu",
        dateOfBirth: "15-03-1985",
        age: 13,
        gender: "Male",
        address: "Orange St. East Legon",
        phoneNumber: "0243869937",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 5,
        name: "Katelyn Boakye",
        dateOfBirth: "31-05-2011",
        age: 18,
        gender: "Female",
        address: "Korlegonnor, Accra",
        phoneNumber: "0266849937",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 6,
        name: "Samuel Nartey",
        dateOfBirth: "03-11-1972",
        age: 34,
        gender: "Male",
        address: "Kwame Nkrumah Circle, Accra",
        phoneNumber: "0203946287",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 7,
        name: "Cynthia Bills",
        dateOfBirth: "23-09-1962",
        age: 54,
        gender: "Female",
        address: "Nima, Accra",
        phoneNumber: "054479347",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 8,
        name: "Jack Harris",
        dateOfBirth: "13-03-1995",
        age: 25,
        gender: "Male",
        address: "Sowutuom, Accra",
        phoneNumber: "0244549937",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 9,
        name: "Mary Jane",
        dateOfBirth: "13-03-1992",
        age: 23,
        gender: "Female",
        address: "Parsnip St. East Legon",
        phoneNumber: "0203049937",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 10,
        name: "Abena Korkor",
        dateOfBirth: "13-03-1992",
        age: 39,
        gender: "Female",
        address: "Parsnip St. East Legon",
        phoneNumber: "0203049937",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 11,
        name: "Akwasi Bini",
        dateOfBirth: "13-03-2009",
        age: 13,
        gender: "Male",
        address: "Algon St. Tema",
        phoneNumber: "0238563945",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 12,
        name: "Esther Owusua",
        dateOfBirth: "20-07-2002",
        age: 19,
        gender: "Female",
        address: "Latebiokorshie, Accra",
        phoneNumber: "0544829306",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 13,
        name: "Jacob Sower",
        dateOfBirth: "13-12-1982",
        age: 34,
        gender: "Male",
        address: "Lapaz, Accra",
        phoneNumber: "0507291726",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 14,
        name: "Cassandra Smalls",
        dateOfBirth: "10-06-1959",
        age: 54,
        gender: "Female",
        address: "Lagoon St Dansoman",
        phoneNumber: "0578192712",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 15,
        name: "Lewis Brown",
        dateOfBirth: "13-03-1992",
        age: 67,
        gender: "Male",
        address: "Awoshie, Accra",
        phoneNumber: "0524808128",
        paymentMethod: "Cash",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 16,
        name: "Simon Adams",
        dateOfBirth: "13-03-1992",
        age: 54,
        gender: "Male",
        address: "Labone, Accra",
        phoneNumber: "0203049937",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
      {
        id: 17,
        name: "Henry Delali",
        dateOfBirth: "13-03-1989",
        age: 29,
        gender: "Male",
        address: "James Town, Accra",
        phoneNumber: "0503647834",
        paymentMethod: "NHIS",
        examDone: false,
        diagnosisDone: false,
      },
    ],
    consultation:[],
    examination: [],
    pharmacy: [],
    account: [],
    record: [],
    patientsHasNewItem: true,
    consultationHasNewItem: false,
    examinationHasNewItem: false,
    pharmacyHasNewItem: false,
    accountHasNewItem: false,
    recordHasNewItem: false,
}

const reducer = (state = initialState, action) => {
    switch (action.type) {
        case 'ADD_NEW_PATIENT': return { ...state, patients:[...state.patients, action.payload], patientsTally:[...state.patientsTally, action.payload], patientsHasNewItem: true }
        case 'ADD_TO_CONSULTATION': return { ...state, consultation:[...state.consultation, action.payload], patients: action.patientList, consultationHasNewItem: true }
        case 'ADD_TO_EXAM': return { ...state, examination:[...state.examination, action.payload], consultation: action.patientList, examinationHasNewItem: true }
        case 'ADD_TO_ACCOUNT': return { ...state, account:[...state.account, action.payload], consultation: action.patientList, accountHasNewItem: true }
        case 'ADD_TO_PHARMACY': return { ...state, pharmacy:[...state.pharmacy, action.payload], account: action.patientList, pharmacyHasNewItem: true }
        case 'ADD_TO_RECORDS': return { ...state, record:[...state.record, action.payload], pharmacy: action.patientList, patientsTally: action.patienTallyList, recordHasNewItem: true }
        case 'UPDATE_CONSULT': return { ...state, consultation: action.payload }
        case 'UPDATE_EXAM': return { ...state, examination: action.patientList , consultation: [ ...state.consultation, action.payload ], consultationHasNewItem: true }
        case 'SET_ACCOUNT_STATUS': return { ...state, accountHasNewItem: false }
        case 'SET_CONSULTATION_STATUS': return { ...state, consultationHasNewItem: false }
        case 'SET_EXMINATION_STATUS': return { ...state, examinationHasNewItem: false }
        case 'SET_PATIENTS_STATUS': return { ...state, patientsHasNewItem: false }
        case 'SET_PHARMACY_STATUS': return { ...state, pharmacyHasNewItem: false }
        case 'SET_RECORD_STATUS': return { ...state, recordHasNewItem: false }
        default: return state;
    }
}

export default reducer;